export const { WeakSet, WeakMap, SyntaxError, RangeError, TypeError, Error, BigInt, Date, parseInt, Infinity, NaN, Map, RegExp,
	Array: { isArray },
	String: { fromCodePoint },
	Number: { isSafeInteger },
	Object: { create, getOwnPropertyNames },
	Reflect: { getPrototypeOf },
	Symbol,
	Symbol: { for: Symbol_for },
	JSON: { stringify },
	Buffer: { isBuffer },
} = global;
